name: Firebase App Distribution

on: push

jobs:
  my-job:
    name: Upload APK to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          PASSPHRASE_DISTRIBUTION: ${{ secrets.PASSPHRASE_DISTRIBUTION }}
      - name: Build release apk
        run: bash ./gradlew assembleRelease appDistributionUploadRelease