name: Firebase App Distribution

on: push

jobs:
  my-job:
    name: Upload APK to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          PASSPHRASE_DISTRIBUTION: ${{ secrets.PASSPHRASE_DISTRIBUTION }}
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
      - name: Test printing your secret (Remove this step in production)
        run: cat $HOME/secrets/movies-d8bf0-96de52f83acf.json