name: Pull Request

on:
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize, edited ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Add secrets
      run: |
        cat > apikey.properties << ENDOFFILE
        TMDB_API_TOKEN=${{ secrets.TMDB_API_TOKEN }}
        ENDOFFILE
    - name: Assemble debug
      run: bash ./gradlew assembleDebug
    - name: Run Unit Tests
      run: bash ./gradlew testDebugUnitTest --stacktrace
